# syntax=docker/dockerfile:1.4

FROM node:22-alpine AS base

# install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

FROM base AS deps

# Copy workspace configs
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY tsconfig.base.json ./
COPY tsconfig.json ./

# # Copy package/json file for all needed packages
COPY packages/common/package.json ./packages/common/
COPY services/auth-service/package.json ./services/auth-service/
# COPY . .

# Install dependencies
RUN pnpm install --frozen-lockfile


FROM deps AS builder

# Copy source code
COPY packages/common ./packages/common
COPY services/auth-service ./services/auth-service

# build common package first
RUN pnpm --filter @chat_app/common build

# build auth-service
RUN pnpm --filter @chat_app/auth-service build


FROM node:22-alpine AS production

# install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Create a non-root user to run the application
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nodeuser

# Set the working directory
WORKDIR /app

# Copy workspace configs
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY tsconfig.base.json ./

# Copy package.json file
COPY packages/common/package.json ./packages/common/
COPY services/auth-service/package.json ./services/auth-service/


# Install only production dependencies
RUN pnpm install --frozen-lockfile --prod

# Copy build artifacts
COPY --from=builder /app/packages/common/dist ./packages/common/dist
COPY --from=builder /app/services/auth-service/dist ./services/auth-service/dist

# Change ownership of the application files to the non-root user
RUN chown -R nodeuser:nodejs /app

# Switch to the non-root user
USER nodeuser

# Expose the port the app runs on
ENV NODE_ENV=production
ENV AUTH_SERVICE_PORT=4003

EXPOSE ${AUTH_SERVICE_PORT}

WORKDIR /app/services/auth-service

CMD ["node", "dist/index.js"]